### ISSUE TITLE
Site unusable on small screens.

### ISSUE THREAD

**Issue by mahkoh** [wycats/cargo-website#3]
http://a.pomf.se/lbjduy.png

And please do not fix it be dynamically hiding and showing stuff. html can deal with different screen sizes just fine without that. Simply removing the width attribute on main fixes it.

**Comment by vladikoff** [comment]
Cannot read stuff on the left or scroll to the left in Chrome or Firefox on small resolutions: (See scrollbar)
![image](https://cloud.githubusercontent.com/assets/128755/3528071/7d348924-078b-11e4-8e7d-e9f30709c4ac.png)

**Comment by mahkoh** [comment]
I see that my file was deleted, but it showed the same problem.
